#!/usr/bin/env node
/**
 * Stop: the verify gate.
 *
 * We write no unit tests, so `tsc --noEmit` + eslint is the floor that
 * replaces them, and a floor nobody can skip has to be enforced rather than
 * requested. This runs the checks itself instead of asking the model whether
 * it remembered to - a prompt hook receives only the event JSON and has no
 * tools, so it cannot know what changed.
 *
 * Exit 2 blocks the stop and shows stderr to Claude as the reason.
 *
 * Deliberately NOT covered here: running the solution in the workbench.
 * That needs an authenticated browser session, so it stays a human-facing
 * instruction in CLAUDE.md - see `spfx-preview`.
 */
const fs = require("fs");
const path = require("path");
const os = require("os");
const { execFileSync } = require("child_process");
const { runLocal } = require("./local-bin");

const MAX_BLOCKS = 2; // then let the session end; a loop helps nobody
const TAIL = 4000;

let raw = "";
process.stdin.on("data", (c) => (raw += c));
process.stdin.on("end", () => {
  let input = {};
  try {
    input = JSON.parse(raw);
  } catch {
    return process.exit(0);
  }

  const root = process.env.CLAUDE_PROJECT_DIR || input.cwd || process.cwd();

  // Not scaffolded yet, or no lint/build available: nothing to gate.
  const pkgPath = path.join(root, "package.json");
  if (!fs.existsSync(pkgPath)) return process.exit(0);

  // Still an uninitialised template: the tokens are not valid TypeScript, so
  // tsc would fail for a reason that has nothing to do with the change being
  // made. `spfx-setup` is the fix, and it is a blocking gate of its own.
  try {
    if (/__[a-z_]+__/.test(fs.readFileSync(pkgPath, "utf8"))) return process.exit(0);
  } catch {
    return process.exit(0);
  }

  const git = (args) => {
    try {
      return execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    } catch {
      return null;
    }
  };

  if (git(["rev-parse", "--is-inside-work-tree"]) === null) return process.exit(0);

  const changed = [
    git(["diff", "--name-only", "HEAD"]),
    git(["diff", "--name-only", "--cached"]),
    git(["ls-files", "--others", "--exclude-standard"]),
  ]
    .filter(Boolean)
    .join("\n")
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);

  const relevant = changed.filter(
    (f) =>
      /\.(ts|tsx|scss)$/.test(f) &&
      !/\.scss\.ts$/.test(f) &&
      !/^(node_modules|lib|dist|temp|release|solution)\//.test(f)
  );
  if (!relevant.length) return process.exit(0);

  // Cap how many times one session may be blocked.
  const stateFile = path.join(os.tmpdir(), `spfx-verify-gate-${input.session_id || "anon"}.json`);
  let blocks = 0;
  try {
    blocks = JSON.parse(fs.readFileSync(stateFile, "utf8")).blocks || 0;
  } catch {
    /* first run this session */
  }
  if (blocks >= MAX_BLOCKS) return process.exit(0);

  const failures = [];
  const notes = [];

  // Typings for `*.module.scss` are generated by Heft into temp/sass-ts, which
  // the rig's tsconfig lists in `rootDirs`. Before the first build they do not
  // exist and tsc reports TS2307 on every stylesheet import - a failure that has
  // nothing to do with the change being made. Say so rather than reporting it.
  if (fs.existsSync(path.join(root, "temp", "sass-ts"))) {
    const tsc = runLocal(root, "tsc", ["--noEmit"]);
    if (tsc) failures.push(["npx tsc --noEmit", tsc]);
  } else {
    notes.push(
      "tsc was skipped: temp/sass-ts does not exist, so *.module.scss has no " +
        "typings yet and tsc would fail on every stylesheet import. Run " +
        "`npx heft build` once to generate them."
    );
  }

  const lint = runLocal(root, "eslint", ["src"]);
  if (lint) failures.push(["npx eslint src", lint]);

  // Rule 1 - no colour literal outside src/theme/ - is a stylelint rule, so a
  // gate that skips stylelint does not enforce it. Only worth running when a
  // stylesheet actually changed.
  if (relevant.some((f) => /\.scss$/.test(f))) {
    const styles = runLocal(root, "stylelint", ["src/**/*.scss"]);
    if (styles) failures.push(['npx stylelint "src/**/*.scss"', styles]);
  }

  if (!failures.length) return process.exit(0);

  try {
    fs.writeFileSync(stateFile, JSON.stringify({ blocks: blocks + 1 }));
  } catch {
    /* best effort */
  }

  const report = failures
    .map(([cmd, out]) => `$ ${cmd}\n${out.length > TAIL ? out.slice(-TAIL) : out}`)
    .concat(notes.map((n) => `Note: ${n}`))
    .join("\n\n");

  console.error(
    `Verify gate: ${relevant.length} source file(s) changed and the build gate does not pass.\n` +
      `Fix these, then finish. Do not report the change as done until they pass.\n\n${report}`
  );
  process.exit(2);
});
